on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: eplusr-paper

jobs:
  build-paper:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest
    container: hongyuanjia/eplusr:9.1.0-verse

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: "https://demo.rstudiopm.com/all/__linux__/xenial/latest"

    steps:
      - uses: actions/checkout@v1

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.9.1.1'

      - name: Query dependencies
        run: Rscript -e "install.packages('remotes')" -e "saveRDS(remotes::dev_package_deps(dependencies = TRUE), 'depends.Rds', version = 2)"

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-r-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Install system dependencies
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"

      - name: Install dependencies
        run: Rscript -e "library(remotes)" -e "update(readRDS('depends.Rds'))"

      - name: Build paper
        run: Rscript -e "rmarkdown::render('vignettes/paper.Rmd', output_dir = here::here('vignettes'))"

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: eplusr-paper
          path: vignettes/paper.pdf
        if: success()
